language: go

go:
  - "1.13.x"
  
matrix:
  include:
    - os: linux-ppc64le
      env: ARCH="ppc64le"

sudo: true

servics:
  - docker

before_install:
  - sudo rm -f /var/lib/dpkg/lock
  - sudo apt-get -qq update
  - sudo apt-get install sshpass -y
  - echo $TRAVIS_OS_NAME
  - echo $ARCH
  - if [[ "$ARCH" == "ppc64le" ]]; then
    curl -H "X-JFrog-Art-Api:$SWG_DEVOPS_REPO_TOKEN" "https://na.artifactory.swg-devops.com/artifactory/sys-powercloud-generic-local/glide-0.12.3-2.tar.gz" --output glide.tar.gz;
    sudo tar zxvf glide.tar.gz -C /usr/local/bin --no-same-owner;
    fi
  - curl https://glide.sh/get | sh
  - echo $TRAVIS_OS_NAME
  - echo $ARCH
# Install all of the dependencies referenced in the glide.yaml file
  - glide cc && glide install -v

before_script:
  # We need to login to docker up-front but only do it if we truly want to publish the images and is a release branch
  #- if [[ "$PUBLISH_DOCKER_IMAGES" == "yes" ]] && [[ "$TRAVIS_BRANCH" == "v"*"."*"."* ]] ; then
  - make docker-login
  #  fi

script:
  # We want to both build the binaries for the golang program
  - make push-image

after_success:
  # Determine if this is a personal branch or the master/v1.0.0 branch and publish differently
