apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: allow hostpath and host network to be accessible
  generation: 1
  name: mycsiaccess
  selfLink: /apis/security.openshift.io/v1/securitycontextconstraints/csiaccess
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
defaultAddCapabilities: []
priority: null
fsGroup:
  type: MustRunAs
groups:
- system:authenticated
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:myproject:my-csi-attacher
- system:serviceaccount:myproject:my-csi-provisioner
- system:serviceaccount:myproject:my-csi-node
- system:serviceaccount:myproject:my-csi-resizer
volumes:
- '*'
